INSERT INTO `tb_animal` (`data_cadastro`, `descricao`, `disponivel`, `especie`,`idade`, `inf_adicionais`, `nome`, `porte`, `raca`, `sexo`)VALUES 
('20220405','Lorem ipsum dolor sit amet, consectetur adipiscing elit.',b'1', 'cachorro',1,'Vacinado e Castrado','Amendoim', 'médio','SRD','macho'),
('20220405','Donec non nunc sed lacus condimentum semper et at erat.',b'1', 'gato',1,'Vacinada e Castrada, FIV e FELV negativo', 'Aurora','pequeno','SRD','fêmea'),
('20220415','Morbi accumsan magna vitae finibus aliquam.',b'1', 'gato',1, 'Vacinado e Castrado, FIV e FELV negativo', 'Felipe', 'médio','SRD','macho'),
('20220416','Pellentesque felis ipsum, pharetra sit amet lacus.',b'1','cachorro',2,'Vacinado e Castrado','Fred', 'pequeno','SRD','macho'),
('20220417','Nulla gravida mauris nunc, vel posuere eros luctus eu.',b'1', 'cachorro',3,'Vacinado e Castrado', 'James', 'pequeno','SRD','macho'),
('20220418','Suspendisse potenti. Etiam sed tempus massa.',b'1', 'gato',2, 'Vacinada e Castrada, FIV negativo, FELV positivo','Francisca', 'médio','SRD','fêmea'),
('20220418','Nam tristique nisl arcu, ac ultricies urna gravida in.',b'1', 'gato',1,'Vacinada e Castrada, FIV e FELV negativo','Lila','médio','SRD','fêmea'),
('20220425','Sed condimentum a tortor blandit tempor.',b'1', 'cachorro',1, 'Vacinado e Castrado', 'Rodolfo', 'médio','SRD','macho'),
('20220425','Etiam sit amet lobortis enim, quis sagittis odio.',b'1','cachorro',1,'Vacinado e Castrado', 'Roger', 'médio','SRD','macho'),
('20220502','Vestibulum lacinia, mi in tempus consequat, massa sapien congue lectus.',b'1','gato',2,'Vacinado e Castrado, FIV positivo e FELV negativo','Salen','médio','SRD','macho'),
('20220506','Lorem ipsum dolor sit amet, consectetur adipiscing elit.',b'1', 'cachorro',1,'Vacinado e Castrado','Spike','médio','SRD','macho'),
('20220705','Donec non nunc sed lacus condimentum semper et at erat.',b'1', 'gato',1,'Vacinada e Castrada, FIV e FELV negativo', 'Isabel','médio','SRD','fêmea'),
('20220514','Morbi accumsan magna vitae finibus aliquam.',b'1', 'cachorro',1,'Vacinado e Castrado', 'Gael','pequeno','SRD','macho'),
('20220516','Pellentesque felis ipsum, pharetra sit amet lacus.',b'1','gato',2,'Vacinada e Castrada, FIV e FELV negativo', 'Lucy','médio','SRD','fêmea'),
('20220518','Nulla gravida mauris nunc, vel posuere eros luctus eu.',b'1', 'gato',3,'Vacinada e Castrada, FIV e FELV negativo','Morgana','médio','SRD','fêmea'),
('20220602','Suspendisse potenti. Etiam sed tempus massa.',b'1', 'cachorro',2, 'Vacinado e Castrado', 'Caramelo', 'médio','SRD','macho'),
('20220604','Nam tristique nisl arcu, ac ultricies urna gravida in.',b'1', 'gato',1,'Vacinado e Castrado, FIV e FELV negativo','Leopoldo','médio','SRD','macho'),
('20220605','Sed condimentum a tortor blandit tempor.',b'1', 'cachorro',1, 'Vacinado e Castrado', 'Jose','médio','SRD','macho'),
('20220612','Etiam sit amet lobortis enim, quis sagittis odio.',b'1','cachorro',1, 'Vacinada e Castrada','Branca','médio','SRD','fêmea'),
('20220625','Vestibulum lacinia, mi in tempus consequat, massa sapien congue lectus.',b'1', 'gato',1, 'Vacinado e Castrado, FIV e FELV negativo','Pietro','médio','SRD','macho')
